<script type="text/javascript" src="/js/bootstrap-datepicker.js"></script>
<?php if ($this->plugin('translate')->getTranslator()->getLocale() == 'en') { ?>
<script type="text/javascript" src="/js/locales/bootstrap-datepicker.js" charset="UTF-8"></script>
<?php } else {?>
<script type="text/javascript" src="/js/locales/bootstrap-datepicker.<?php echo $this->plugin('translate')->getTranslator()->getLocale()?>.js" charset="UTF-8"></script>
<?php } ?>
<script type="text/javascript" src="/js/bootstrap-timepicker.min.js"></script>
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
<script type="text/javascript">
var nowTemp = new Date();
var now = new Date(nowTemp.getFullYear(), nowTemp.getMonth(), nowTemp.getDate(), 0, 0, 0, 0);
var data1 = "";
$(window).load(function(){

    $('#data').datepicker({
        weekStart: 1,
        startDate: now,        
        autoclose: true
        });
	  
$('#reservation_time').timepicker({showMeridian :false,  showSeconds: false, defaultTime : false, disableFocus: true});

});

function checkpostimenu()
{
	var $alert = "<center><img src='/images/bigLoader.gif' /></center>";
	$('#alert').css({"height":'50px'});	
	$('#alert').html($alert);	
	var nummenu = Number($('#reservation_num_menu').val());
	var numposti = Number($('#reservation_num_posti').val());
	if (typeof nummenu === "undefined") {nummenu = 0;}
	if (typeof numposti === "undefined") {numposti = 0;}
	if (nummenu > numposti)
	{
		$('#submitbutton').prop('disabled', true);
		var $alert = "<div class='alert alert-error'> <?php echo $this->translate('Il numero delle persone è minore del numero dei menu') ?>  </div>";
		$('#alert').html($alert);		
	}
	else
	{
		$('#submitbutton').prop('disabled', false);
		$('#alert').css({"height":'0px'});
		var $alert = "";
		$('#alert').html($alert);			
	}
};

function check()
{
	var $alert = "<center><img src='/images/bigLoader.gif' /></center>";
	var str = $('#reservation_date').val();
	var res = str.replace(/[^a-zA-Z0-9]/g, "-"); 
	$('#alert').css({"height":'50px'});	
	$('#alert').html($alert);	
	$.ajax({		
		url: "/check/" + <?php echo $this->escapeHtml($proposta['id_proposta']); ?> + '/' + res + '/' + $('#reservation_time').val() + '/' + $('#reservation_num_posti').val() + '/' + $('#reservation_num_menu').val(),
		success: function(json){
			var obj = jQuery.parseJSON(json);
			if(obj.status == 'ok'){			
				$('#submitbutton').prop('disabled', false);
				$('#alert').css({"height":'0px'});
				var $alert = "";
				$('#alert').html($alert);
				checkpostimenu;	
			}else{				
				$('#submitbutton').prop('disabled', true);	
				var $alert = "<div class='alert alert-error'><?php echo $this->translate('Proposta non valida per Data / Ora Selezionati') ?></div>";
				$('#alert').html($alert);
			}
		}
	});	
};	




var map;
$(function() {

	$('#reservation_date').on('change', check);	
	$('#reservation_time').on('changeTime.timepicker', check);	
	$('#reservation_num_posti').on('change', checkpostimenu);			
	$('#reservation_num_menu').on('change', checkpostimenu);		
	$('#tab_mappa').on('shown', function(e) {
		if( map == undefined) {
			myLatlng = new google.maps.LatLng(<?php echo $this->escapeHtml($ristorante['lat']); ?>, <?php echo $this->escapeHtml($ristorante['lng']); ?>);
			  var mapOptions = {
					    zoom: 15,
					    center: myLatlng,
					    mapTypeId: google.maps.MapTypeId.ROADMAP
					  };								
			map = new google.maps.Map(document.getElementById("map_canvas"), mapOptions);

			  var marker = new google.maps.Marker({
			      position: myLatlng,
			      map: map,
			      title: ''
			  });
			  			
			//google.maps.event.addDomListener(window, 'load', initialize);
		};
	});
	
});
	

</script>

<?php
$reservation_form = $this->quickreservation_form;
$reservation_form->setAttribute('class', 'form-vertical');
$reservation_form->prepare();

?>
<div id="main" class="container">
<div class="row-fluid">
	<div class="span10 offset1">
		<h1>
		<?php  echo $this->escapeHtml($proposta['titolo_proposta']); ?>
		</h1>
	
				<div class="row-fluid">
					<div class="span8">
						<div class="row-fluid">
						
							<div class="widget-box">
								<div class="widget-title">
									<ul class="nav nav-tabs">
										<li class="active"><a href="#tab1" data-toggle="tab"><?php echo $this->translate('Foto') ?></a>
										</li>
										<li><a href="#tab2"  data-toggle="tab"><?php echo $this->translate('Ristorante') ?></a>
										</li>
										<li><a href="#tab3" id="tab_mappa" data-toggle="tab"><?php echo $this->translate('Mappa') ?></a>
										</li>
									</ul>

								</div>
								<div class="widget-content tab-content">
									<div id="tab1" class="tab-pane active">
										<div class="span12" id="slider">
											<!-- Top part of the slider -->

											<div id="carousel-bounding-box">
												<div id="myCarousel" class="carousel slide">

													<!-- Carousel items -->
													<div class="carousel-inner">
													<?php $i = 0;?>	
													<?php if (count($proposta['id_images']) == 0 ) { echo "<img src='/proposte/images/PLlogopng' />"; };?>											
													<?php foreach ($proposta['id_images'] as $row => $key) : ?>
														<div class="<?php if ($i == 0) { echo 'active item'; } else { echo 'item';};?>" data-slide-number="<?php echo $this->escapeHtml($key);?>">
															<img src="/proposte/images/PL<?php echo $this->escapeHtml($key); ?>" />
															<h4><?php 
																	foreach ($proposta['piatti'] as $row1 => $key1) :																	
																		if ($key == $key1['id_piatto'])
																		{
																			echo $this->escapeHtml($this->translate($key1['desc_tipo_piatto']));																	
																		}
																	endforeach; 
																?>
															</h4>
														</div>
													<?php $i = $i +1 ?>	
													<?php endforeach; ?>
													</div>
													<!-- Carousel nav -->
													<?php if($i > 1) {?>
													<a class="carousel-control left" href="#myCarousel"
														data-slide="prev">‹</a> <a class="carousel-control right"
														href="#myCarousel" data-slide="next">›</a>
													<?php }?>
												</div>
											</div>
										</div>
									</div>
									<div id="tab2" class="tab-pane">
									<ul class="recent-posts">
									<li>
										<address>
											<strong><?php echo $this->escapeHtml($ristorante['nome']); ?></strong><br>
											<?php echo $this->escapeHtml($ristorante['indirizzo']); ?><br>
											<?php echo $this->escapeHtml($ristorante['provincia']); ?><br>
											<?php echo $this->escapeHtml($ristorante['descrizione']); ?>
										</address>
									</li>
									<li>
										<div class="span12" id="slider">
											<!-- Top part of the slider -->

											<div id="carousel-bounding-box">
												<div id="myCarousel1" class="carousel slide">

													<!-- Carousel items -->
													<div class="carousel-inner">
													<?php $i = 0;?>												
													<?php foreach ($ristorante['id_photo'] as $row => $key) : ?>
														<div class="<?php if ($i == 0) { echo 'active item'; } else { echo 'item';};?>" data-slide-number="<?php echo $this->escapeHtml($i);?>">
															<img src="/proposte/images/RL<?php echo $this->escapeHtml($key); ?>" />
														</div>
													<?php $i = $i +1 ?>	
													<?php endforeach; ?>
													</div>
													<!-- Carousel nav -->
													<?php if($i > 1) {?>
													<a class="carousel-control left" href="#myCarousel1"
														data-slide="prev">‹</a> <a class="carousel-control right"
														href="#myCarousel1" data-slide="next">›</a>
													<?php }?>
												</div>
											</div>
										</div>
										</li>
										</ul>								
									</div>
									<div id="tab3" class="tab-pane">
										<div id="map_canvas" style="height: 400px; witdh :500px;"></div>
									</div>
								</div>
							</div>
						</div>
						<div class="row-fluid">
							<div class="widget-box">
								<div class="widget-title">
									<ul class="nav nav-tabs">
										<li class="active"><a href="#tab4" data-toggle="tab"><?php echo $this->translate('Proposta') ?></a>
										</li>
										<li><a href="#tab5" data-toggle="tab"><?php echo $this->translate('Servizi') ?></a>
										</li>
										<li><a href="#tab6" data-toggle="tab"><?php echo $this->translate('Orari') ?></a>
										</li>
									</ul>

								</div>
								<div class="widget-content tab-content">
									<div id="tab4" class="tab-pane active">
										<p>
											<strong><?php echo $this->translate('Tipo di cucina') ?> : </strong>
											<?php echo $this->escapeHtml($this->translate($proposta['tipologia'])); ?>
										</p>
										<h5><?php echo $this->translate('Piatti') ?></h5>
										<?php foreach ($proposta['piatti'] as $row => $key) : ?>
										<p>
											<strong><?php echo $this->escapeHtml($this->translate($key['desc_tipo_piatto'])); ?>
												: <?php echo $this->escapeHtml($key['nome']); ?> </strong> <br>
												<?php echo $this->escapeHtml($key['descrizione']); ?>
										</p>
										<?php endforeach;?>
										<?php
										if ($proposta['note']) { echo "<strong>Note</strong><p>" .$proposta['note']. "</p>"; }; ?>
									</div>
									<div id="tab5" class="tab-pane">
										<div>
											<ul class="recent-posts">
											<?php foreach ($servizi as $row => $key) : ?>
												<li><span class="badge badge-success"> <i
														class="icon-ok icon-white"></i> </span> <?php echo $this->escapeHtml($this->translate($key)); ?>
												</li>
												<?php endforeach;?>
											</ul>
										</div>
									</div>
									<div id="tab6" class="tab-pane">
										<table class="table table-striped">

											<tbody>
											<?php foreach ($apertura as $row => $key) : ?>
												<tr>
													<td><?php echo $this->escapeHtml($this->translate($row)); ?></td>
													<td><?php echo $this->escapeHtml(substr($key['apertura_1'],0,5)); ?>
														/ <?php echo $this->escapeHtml(substr($key['chiusura_1'],0,5)); ?>
													</td>
													<td><?php echo $this->escapeHtml(substr($key['apertura_2'],0,5)); ?>
														/ <?php echo $this->escapeHtml(substr($key['chiusura_2'],0,5)); ?>
													</td>
												</tr>
												<?php endforeach;?>
											</tbody>
										</table>
									</div>
								</div>
							</div>
						</div>
						<div class="row-fluid">						 
							<div class="widget-box">
								<div class="widget-title">
									<h5><?php echo $this->translate('Le altre proposte del Ristoratore') ?></h5>
								</div>
								<div class="widget-content">
									<ul class="recent-posts" id="proposte">								
									<?php $proposte = array ('proposte' => $altre_proposte);?>
									<?php echo $this->partial('portale/proposte/proposte_lista', $proposte); ?>
									</ul>								
								</div>
							</div>
						</div>
						
					</div>

					
					<div class="span4">
						<div class="row-fluid">
							<div class="widget-box">
								<div class="widget-content">		
									<h1 style="text-align:center;">									
									<?php  echo $this->escapeHtml($proposta['prezzo']) . ' ';?> € <small>/ Pers.</small>
									</h1>									
									<?php echo $this->form()->openTag($reservation_form);?>								
									<?php echo $this->formInput($reservation_form->get('id')); ?>	
									<div class="row-fluid">
										<div class="span3 offset2">
											<div class="input-append date" id="data" data-date=""">
						                   	<?php echo $this->formInput($reservation_form->get('reservation_date')); ?>									
											<span class="add-on"><i class="icon-calendar"></i> </span>						
											</div>
										</div>
									</div>
									<div class="row-fluid">
										<div class="span3 offset2">
											<div class="input-append bootstrap-timepicker">
						                   	<?php echo $this->formInput($reservation_form->get('reservation_time')); ?>									
											<span class="add-on"><i class="icon-time"></i> </span>						
											</div>
										</div>
									</div>						
									<div class="row-fluid">
										<div class="span3 offset2">											
						                   	<?php echo $this->formSelect($reservation_form->get('reservation_num_posti')); ?>																																					
										</div>
									</div>					
									<div class="row-fluid">
										<div class="span3 offset2">											
						                   	<?php echo $this->formSelect($reservation_form->get('reservation_num_menu')); ?>																																					
										</div>
									</div>
									<div id="alert"></div>																
									<div class="form-actions" style="text-align:center;">
									<?php echo $this->formSubmit($reservation_form->get('prenota')) ;?>
									</div>
									<?php echo $this->form()->closeTag($reservation_form); ?>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
</div>